"use client";
import {useCallback,useEffect,useState} from 'react';import {useAuth} from '@/providers/AuthProvider';
type Health={gmail_push_status:string;queue:{status:string;depth:number;oldest_job_age_seconds:number|null;last_completed_job:string|null;last_failed_job:string|null;completed_24h:number;failed_24h:number;dead_letter_24h:number;retry_rate:number;provider_429_count:number;provider_503_count:number};classifier:{gemini:string;cooldown_until:string|null;ollama:string};training:{collection:string;rows:number;retention_days:number};push_intake:Array<{last_push:string|null;last_completed:string|null;error:string|null}>};
type Job={id:string;status:string;history_id:string;notification_id:string;intake_request_id:string|null;message_id:string|null;thread_id:string|null;attempts:number;last_error:string|null;last_provider_status:number|null;created_at:string};
function age(seconds:number|null){if(seconds===null)return 'None';if(seconds<60)return `${seconds}s`;if(seconds<3600)return `${Math.floor(seconds/60)}m`;return `${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;}
export default function DeveloperHealth(){const {session}=useAuth(),token=session?.access_token;const [health,setHealth]=useState<Health|null>(null),[jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;setError('');try{const headers={Authorization:`Bearer ${token}`};const [h,q]=await Promise.all([fetch('/api/debug/health',{headers,cache:'no-store'}),fetch('/api/debug/gmail-queue',{headers,cache:'no-store'})]);if(!h.ok||!q.ok)throw Error('Operational status is unavailable');setHealth(await h.json());setJobs((await q.json()).jobs??[]);}catch(e){setError(String(e));}},[token]);
 useEffect(()=>{void load();},[load]);async function act(action:string,id?:string){if(!token||busy)return;setBusy(true);try{const response=await fetch('/api/debug/gmail-queue',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,id})});if(!response.ok)throw Error((await response.json()).error);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 if(!token)return <main className="settings-page"><h1>Developer Health</h1><p>Sign in to view operational status.</p></main>;
 return <main className="settings-page"><header className="settings-header"><p>Developer · deterministic status</p><h1>System Health</h1><button disabled={busy} onClick={()=>void load()}>Refresh</button></header>{error?<p role="alert">{error}</p>:null}{!health?<p role="status">Loading…</p>:<><section className="settings-group" aria-label="Operational health"><div className="settings-row"><span>Gmail intake</span><strong>{health.gmail_push_status}</strong></div><div className="settings-row"><span>Processing queue</span><strong>{health.queue.status} · {health.queue.depth} waiting</strong></div><div className="settings-row"><span>Oldest waiting</span><strong>{age(health.queue.oldest_job_age_seconds)}</strong></div><div className="settings-row"><span>Gemini</span><strong>{health.classifier.gemini}</strong></div><div className="settings-row"><span>Ollama</span><strong>{health.classifier.ollama}</strong></div><div className="settings-row"><span>Training collection</span><strong>{health.training.collection} · {health.training.rows} rows · {health.training.retention_days===-1?'forever':`${health.training.retention_days}d`}</strong></div></section><section className="settings-group" aria-label="Queue metrics"><div className="settings-row"><span>Completed / failed / dead letter (24h)</span><strong>{health.queue.completed_24h} / {health.queue.failed_24h} / {health.queue.dead_letter_24h}</strong></div><div className="settings-row"><span>Provider 429 / 503 attempts</span><strong>{health.queue.provider_429_count} / {health.queue.provider_503_count}</strong></div><div className="settings-row"><span>Retry rate</span><strong>{(health.queue.retry_rate*100).toFixed(1)}%</strong></div><div className="settings-row"><span>Last completed</span><strong>{health.queue.last_completed_job??'None'}</strong></div></section></>}
 <header className="settings-header"><h2>Failed and dead-letter jobs</h2><button disabled={busy||!jobs.some(j=>['failed','dead_letter'].includes(j.status))} onClick={()=>void act('retry_all')}>Retry all</button></header>{jobs.filter(j=>['failed','dead_letter','retry_wait'].includes(j.status)).map(job=><section className="settings-group training-example" key={job.id}><p>{job.status} · history {job.history_id} · attempt {job.attempts}{job.last_provider_status?` · HTTP ${job.last_provider_status}`:''}</p><details><summary>Inspect safe payload</summary><p>{job.last_error??'No failure reason recorded'}</p><p>Message {job.message_id??'not resolved'} · thread {job.thread_id??'not resolved'}</p><p>Push {job.notification_id} · request {job.intake_request_id??'legacy'}</p><p>Created {job.created_at}</p></details><div className="training-actions"><button disabled={busy} onClick={()=>void act('retry',job.id)}>Retry</button><button disabled={busy} onClick={()=>void act('resolve',job.id)}>Mark resolved</button></div></section>)}</main>;
}
