import {NextRequest,NextResponse} from 'next/server';import {requireApiUser,ApiAuthError} from '@/lib/serverAuth';import {getServiceSupabaseClient} from '@/lib/supabaseServer';import {ollamaConfiguration} from '@/lib/ai/ollama';
export const runtime='nodejs';const headers={'Cache-Control':'no-store'};
export async function GET(request:NextRequest){try{const user=await requireApiUser(request),db=getServiceSupabaseClient();if(!db)throw Error();const [datasets,runs,candidates,evals,deployments,permissions,baseline,usage,shadows]=await Promise.all([
 db.from('model_dataset_versions').select('id,name,version,example_count,content_hash,created_at,invalidated_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5),
 db.from('model_training_runs').select('id,base_model,method,status,hardware,created_at,completed_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5),
 db.from('model_candidates').select('id,name,version,base_model,ollama_model_name,status,eval_score,weighted_eval_score,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(10),
 db.from('model_eval_runs').select('id,candidate_id,status,metrics,gates_passed,started_at,completed_at').eq('user_id',user.id).order('started_at',{ascending:false}).limit(5),
 db.from('model_deployments').select('id,candidate_id,ollama_model_name,status,deployed_at,ended_at').eq('user_id',user.id).order('deployed_at',{ascending:false}).limit(10),
 db.from('local_model_task_permissions').select('task_type,enabled,min_accuracy,min_confidence,updated_at').eq('user_id',user.id).order('task_type'),
 db.from('model_baselines').select('model_name,correct,total,accuracy,notes,model_benchmark_versions(name,version)').eq('model_name','gemma-4b').limit(1).maybeSingle(),
 db.from('ai_usage_events').select('event_type').eq('user_id',user.id).gte('created_at',new Date(Date.now()-30*86400000).toISOString()).limit(5000),
 db.from('model_shadow_predictions').select('id',{count:'exact',head:true}).eq('user_id',user.id)
 ]);const all=[datasets,runs,candidates,evals,deployments,permissions,baseline,usage,shadows];const failure=all.find(item=>item.error)?.error;if(failure)throw failure;const events=usage.data??[],count=(type:string)=>events.filter(e=>e.event_type===type).length,local=count('local_accepted'),cloud=count('gemini_request')+count('gemini_fallback'),deterministic=count('deterministic'),avoided=deterministic+local,lastMetrics=(evals.data?.[0]?.metrics??{}) as Record<string,unknown>,requestCost=Number(process.env.GEMINI_ESTIMATED_REQUEST_COST_USD??0);return NextResponse.json({ollama:{...ollamaConfiguration(),baseUrl:undefined},current:(deployments.data??[]).find(item=>item.status==='active')??null,datasets:datasets.data??[],runs:runs.data??[],candidates:candidates.data??[],evaluations:evals.data??[],deployments:deployments.data??[],permissions:permissions.data??[],baseline:baseline.data??{model_name:'gemma-4b',correct:6,total:12,accuracy:.5},shadow_predictions:shadows.count??0,cost_metrics:{deterministic_requests:deterministic,local_requests:local,cloud_requests:cloud,gemini_requests_avoided:avoided,estimated_cloud_cost_avoided_usd:Number.isFinite(requestCost)?avoided*requestCost:0,local_resolution_rate:local+cloud?local/(local+cloud):0,average_recorded_latency_ms:typeof lastMetrics.average_latency_ms==='number'?lastMetrics.average_latency_ms:null}},{headers});}catch(error){return NextResponse.json({error:error instanceof ApiAuthError?error.message:'Model registry unavailable'},{status:error instanceof ApiAuthError?error.status:500,headers});}}
export async function PATCH(request:NextRequest){try{const user=await requireApiUser(request),db=getServiceSupabaseClient();if(!db)throw Error();const body=await request.json() as {taskType?:string;enabled?:boolean;minAccuracy?:number;minConfidence?:number};if(!body.taskType||typeof body.enabled!=='boolean'||!/^[a-z0-9_]{2,80}$/.test(body.taskType))return NextResponse.json({error:'Invalid task permission'},{status:400,headers});const minAccuracy=body.minAccuracy??.95,minConfidence=body.minConfidence??.97;if(![minAccuracy,minConfidence].every(value=>Number.isFinite(value)&&value>=0&&value<=1))return NextResponse.json({error:'Thresholds must be between 0 and 1'},{status:400,headers});const result=await db.from('local_model_task_permissions').upsert({user_id:user.id,task_type:body.taskType,enabled:body.enabled,min_accuracy:minAccuracy,min_confidence:minConfidence,updated_at:new Date().toISOString()},{onConflict:'user_id,task_type'});if(result.error)throw result.error;return NextResponse.json({ok:true},{headers});}catch(error){return NextResponse.json({error:error instanceof ApiAuthError?error.message:'Task permission update failed'},{status:error instanceof ApiAuthError?error.status:500,headers});}}
