"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useAuth} from "@/providers/AuthProvider";
type Usage={from:string;counts:Record<string,number>;averageAcceptedConfidence:number|null;fallbackRate:number|null;coverage:string};
export default function AIUsage(){const {session}=useAuth();const [usage,setUsage]=useState<Usage|null>(null),[error,setError]=useState("");
useEffect(()=>{setUsage(null);setError("");if(!session?.access_token)return;const controller=new AbortController();void fetch("/api/debug/ai",{headers:{Authorization:`Bearer ${session.access_token}`},signal:controller.signal,cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setUsage(body);}).catch(error=>{if(!controller.signal.aborted)setError(String(error));});return()=>controller.abort();},[session?.access_token]);
const labels=[['gemini_request','Gemini request attempts'],['ollama_request','Ollama request attempts'],['deterministic','Deterministic resolutions'],['cache_hit','Cached analyses reused'],['escalation','Local escalations'],['local_accepted','Accepted local predictions'],['gemini_fallback','Gemini fallback attempts'],['failure','Failed analyses']];
return <main className="settings-page"><header className="settings-header"><p>Developer · today (UTC)</p><h1>AI Usage</h1><Link href="/profile">Back to Settings</Link></header>{error?<p role="alert">{error}</p>:null}{!session?<p>Sign in to view your usage.</p>:!usage&&!error?<p role="status">Loading usage…</p>:null}{usage?<><section className="settings-group" aria-label="AI usage today">{labels.map(([key,label])=><div className="settings-row" key={key}><span>{label}</span><strong>{usage.counts[key]??0}</strong></div>)}<div className="settings-row"><span>Accepted Gemma average confidence</span><strong>{usage.averageAcceptedConfidence===null?'Not available':`${(usage.averageAcceptedConfidence*100).toFixed(1)}%`}</strong></div><div className="settings-row"><span>Fallback share of Gemini attempts</span><strong>{usage.fallbackRate===null?'Not available':`${(usage.fallbackRate*100).toFixed(1)}%`}</strong></div></section><p>{usage.coverage}</p><p>Gemini calls avoided are not estimated: batched calls, retries, and cached analysis sizes differ. No historical usage is backfilled.</p></>:null}</main>;}
